export const projects = [{
        title: 'Weather App',
        description: "Using React, Node.js, Express & PostgresSQL, Worked on a group project with a team of 4 members as part of TTP capstone project.Developed a web application for users to check the weather, save their favorite location. I worked on front-end home page which tells user current weather based on location using open cage geolocation ",
        image: '/images/weather.png',
        tags: ['PostgresSQL', 'Express', 'React', 'Node', 'Opencage'],
        source: 'https://github.com/FaraiMajor/WeatherRangers_frontend',
        visit: 'https://weather-rangers-frontend.herokuapp.com/',
        id: 0,
    },
    {
        title: 'Bank of React',
        description: "The goal of this project was to describe the difference between server-side and client-side routing and Understand built in React Router components (Route, Router, Switch, Link, Redirect). Worked on this project with a group of 3 members. This project is a simple banking interface allowing user to add debits and credit and pull data from an API",
        image: '/images/bank.png',
        tags: ['React', 'JavaScript', 'CSS'],
        source: 'https://github.com/FaraiMajor/Bank-of-React',
        visit: 'https://google.com',
        id: 1,
    },
    {
        title: 'Grid Coloring',
        description: "This was another project to further demonstrate an understanding of HTML, CSS, JS, DOM manipulation, and handling user events with ReactJS. This is also an opportunity to for improving organization in a React application",
        image: '/images/grid.png',
        tags: ['React', 'CSS', 'HTML'],
        source: 'https://github.com/FaraiMajor/react-grid',
        visit: 'https://hyeranpark99.github.io/Group7_Assignment8/',
        id: 2,
    },
    {
        title: 'Recipes from Zimbabwe',
        description: "Developed project to share with users the cultural dishes from Africa allowing users to find recipes of their choosing from the ones available and give them step by step instructions, project uses HTML and CSS. This is an ongoing project",
        image: '/images/recipe.png',
        tags: ['HTML', 'CSS'],
        source: 'https://github.com/FaraiMajor/recipe-project',
        visit: 'https://faraimajor.github.io/recipe-project/',
        id: 3,
    },
];

export const TimeLineData = [
    { year: 2019, text: 'Started my journey', },
    { year: 2020, text: 'Enrolled at Brooklyn college', },
    { year: 2021, text: 'Took my first programmin course(Java)', },
    { year: 2021, text: 'Shared my projects with the world', },
    { year: 2022, text: 'Completed a Web Dev bootcamp with TTP', },
];