export const projects = [{
        title: 'Weather App',
        description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
        image: '/images/weather.png',
        tags: ['PostgresSQL', 'Express', 'React', 'Node', 'Opencage'],
        source: 'https://github.com/FaraiMajor/WeatherRangers_frontend',
        visit: 'https://weather-rangers-frontend.herokuapp.com/',
        id: 0,
    },
    {
        title: 'Bank of React',
        description: "While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
        image: '/images/bank.png',
        tags: ['React', 'JavaScript', 'CSS'],
        source: 'https://github.com/FaraiMajor/Bank-of-React',
        visit: 'https://google.com',
        id: 1,
    },
    {
        title: 'Grid Coloring',
        description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
        image: '/images/grid.png',
        tags: ['React', 'CSS', 'HTML'],
        source: 'https://github.com/FaraiMajor/react-grid',
        visit: 'https://hyeranpark99.github.io/Group7_Assignment8/',
        id: 2,
    },
    {
        title: 'Recipes from Zimbabwe',
        description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
        image: '/images/recipe.png',
        tags: ['HTML', 'CSS'],
        source: 'https://github.com/FaraiMajor/recipe-project',
        visit: 'https://faraimajor.github.io/recipe-project/',
        id: 3,
    },
];

export const TimeLineData = [
    { year: 2019, text: 'Started my journey', },
    { year: 2020, text: 'Enrolled at Brooklyn college', },
    { year: 2021, text: 'Took my first programmin course(Java)', },
    { year: 2021, text: 'Shared my projects with the world', },
    { year: 2022, text: 'Completed a Web Dev bootcamp with TTP', },
];